# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitcomments',
            name='rating',
            field=models.CharField(max_length=30),
        ),
    ]
